settings:
    wav_paths:
    - wavs
    img_paths:
    - images
    out_path: amusic_tmp
    conv_path: mp3s_tmp
    sox_params: ["-C", "320"]
    conv_ext: .mp3
    min_img_size: [640, 480]
aclip.wav:
    folder_name: berlioz_funebre
    img_fname: brown_team.jpg
    album: Symphonie Funèbre et Triomphale Op 15
    albumartist: Hector Berlioz
    albumartistsort: Berlioz, Hector
    artist: Hector Berlioz
    artists: Hector Berlioz
    artistsort: Berlioz, Hector
    composer: Hector Berlioz
    conductor: Fritz Straub
    title: 'Symphonie Funèbre et Triomphale Op 15: Marche funèbre'
    soloists:
    - Helmut Schmitt
    originalyear: 1953
    discnumber: 1
    disctotal: 1
    tracknumber: 1
    tracktotal: 2
    period: Romantic
    style: Symphony
